Repository SeattleColleges/belindas-closet-nestjs, pull requests merged in 2023-08, with the labels that each got.

#6 belindas-closte-nestjs_4_5_initial-db-connection
  .env.sample
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
Labels: Sprint 4

#9 belindas-closet-nestjs_4_7_edit-issue-template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug, Sprint 4, Project Management

#14 belinda-nestjs-5-11_12_13-schema_service_controller_creation
  .eslintrc.js
  src/app.module.ts
  src/products/products.controller.spec.ts
  src/products/products.controller.ts
  src/products/products.module.ts
  src/products/products.service.spec.ts
  src/products/products.service.ts
  src/products/schemas/product.schema.ts
Labels: Sprint 5
