Repository SeattleColleges/belindas-closet-nestjs, pull requests merged in 2023-11, with the labels that each got.

#34 belindas-closet-nestjs_2_24_admin-role
  src/app.module.ts
  src/auth/jwt.guard.ts
  src/auth/role.guard.ts
  src/auth/roles.decorator.ts
  src/products/controllers/products/products.controller.ts
  src/products/services/products/products.service.ts
Labels: Sprint 2

#49 belinda_nestjs_46_update-user-schema
  src/auth/dto/signup.dto.ts
  src/auth/services/auth.service.ts
  src/user/controllers/user/user.controller.ts
  src/user/schemas/user.schema.ts
  src/user/services/user/user.service.ts
Labels: enhancement

#51 Belinda's-Closet-NestJS_3_50_refactor-User-to-DTO
  src/auth/dto/login.dto.ts
  src/user/controllers/user/user.controller.ts
  src/user/dto/update-user.dto.ts
  src/user/services/user/user.service.ts
Labels: enhancement, Sprint 3

#53 Belinda's-Closet-NestJS_3_52_refactor-product-controller
  src/products/controllers/products/products.controller.ts
Labels: enhancement, Sprint 3

#48 Belinda's-Closet-NestJS_3_47_Unit-Tests-User-Controller-and-Service
  src/user/controllers/user/user.controller.spec.ts
  src/user/controllers/user/user.controller.ts
  src/user/services/user/user.service.spec.ts
  src/user/services/user/user.service.ts
  src/user/user.module.ts
Labels: Sprint 3

#56 belindas-closet-nestjs_3_55_add_boolean_ishidden_property
  package-lock.json
  package.json
  src/products/controllers/products/products.controller.ts
  src/products/dto/create-product.dto.ts
  src/products/dto/update-product.dto.ts
  src/products/schemas/product.schema.ts
  src/products/services/products/products.service.ts
Labels: enhancement, Sprint 3

#44 Belinda's-Closet-NestJS_3_112_Unit-Tests-Product-Controller-and-Service
  src/products/controllers/products/products.controller.spec.ts
  src/products/controllers/products/products.controller.ts
  src/products/products.module.ts
  src/products/schemas/product.schema.ts
  src/products/services/products/products.service.spec.ts
  src/products/services/products/products.service.ts
Labels: Sprint 3

#58 belindas-closet-nestjs_3_57_add-issold-property
  src/products/controllers/products/products.controller.ts
  src/products/dto/create-product.dto.ts
  src/products/dto/update-product.dto.ts
  src/products/schemas/product.schema.ts
  src/products/services/products/products.service.ts
Labels: enhancement, Sprint 3

#61 belindas-closet-nestjs_3_60_add-archive-functionality-to-button
  src/products/services/products/products.service.ts
Labels: enhancement, Sprint 3

#64 belindas-closet-nestjs_3_63_update-delete-function-id-parameter
  src/products/services/products/products.service.ts
Labels: enhancement, Sprint 3

#65 belindas_closet_nestjs_4_142_add_appropriate_mit_licensing-to-each_repository
  LICENSE
Labels: documentation, Sprint 4

#67 FIX: Rename LICENSE to LICENSE.md
  LICENSE.md
Labels: documentation, Sprint 4

#69 belinda's-closet_3_refactored-product_59
  src/products/controllers/products/products.controller.spec.ts
  src/products/dto/create-product.dto.ts
  src/products/dto/update-product.dto.ts
  src/products/schemas/product.schema.ts
  src/products/services/products/products.service.spec.ts
Labels: Sprint 4, Sprint 3
