Repository SeattleColleges/belindas-closet-nestjs, pull requests merged in 2024-03, with the labels that each got.

#89 belinda-nestjs-04-88-implement-change-password
  src/auth/controllers/auth.controller.ts
  src/auth/decorator/user.decorator.ts
  src/auth/dto/change-password.dto.ts
  src/auth/dto/product-key.dto.ts
  src/auth/services/auth.service.ts
Labels: Sprint 4

#92 nsc-events-android_4_91_delete_find_stale_templates
  docs/pull_request_template.md
Labels: bug, Sprint 4

#94 Add role decorator, RoleGuard, and JWTAuthGuard to update user api
  src/user/controllers/user/user.controller.ts
Labels: enhancement, Sprint 4

#98 belinda-nest-4-97-adding-product-owner-01
  src/products/controllers/products/products.controller.spec.ts
  src/products/controllers/products/products.controller.ts
  src/products/dto/create-product.dto.ts
  src/products/dto/update-product.dto.ts
  src/products/schemas/product.schema.ts
  src/products/services/products/products.service.spec.ts
  src/products/services/products/products.service.ts
Labels: Sprint 4
